#!/usr/bin/node

let number = [2, 10, 4, 3, 9, 8]

for(let i = 0; i < number.length; i++) {
    for (let j = 0; j < (number.length - i); j++) {
        if (number[j] > number[j + 1 ]) {
            let temp = number[j]
            number[j] = number[j+1]
            number[j+1] = temp
        }
    }
}

console.log(number);
