#!/usr/bin/node
// Find the length of an array

let number = [2, 5, 7, 6, 4, 10, 9]

count = 0;
for (let i = 0; i < number.length; i++) {
    if (number[i] !== null) {
        count += 1
    };
}

console.log(count);
